[[redirects]]
  from = "/guide/"
  to = "/guide/introduction.html"

[[redirects]]
 from = "guide/doc-style-guide.html"
 to = "/guide/contributing/doc-style-guide.html"

[[redirects]]
  from = "/guide/writing-guide.html"
  to = "/guide/contributing/writing-guide.html"


#[build]
#  publish = "dist"
#  command = "npm run generate"
#[build.environment]
#  NODE_VERSION = "11"
[[redirects]]
  from = "/v2/*"
  to = "https://quirky-turing-2f3e2c.netlify.app/v2/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}

[[redirects]]
  from = "/guide/*"
  to = "/v3/guide/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  headers = {X-From = "Netlify"}
